#include "machine/modding/ModDirectoryLoader.hpp"
#include <cassert>
#include <fstream>
#include <cstdlib>

int main()
{
    using namespace BMMQ::Modding;
    auto pattern = (std::filesystem::temp_directory_path() / "time-mod-XXXXXX").string();
    const auto* dir = mkdtemp(pattern.data());
    assert(dir);
    const std::filesystem::path root(dir);
    struct Cleanup { std::filesystem::path path; ~Cleanup() { std::filesystem::remove_all(path); } } cleanup{root};
    const std::vector<std::filesystem::path> dirs{root};
    const std::vector<std::uint8_t> rom{'a', 'b', 'c'};
    const std::string prefix = R"({"schemaVersion":1,"id":"demo","version":"1","target":"gameboy","romSha256":"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" )";
    auto manifest = [&](const std::string& tail) { std::ofstream(root / "manifest.json") << prefix << tail; };
    auto load = [&] { return loadModDirectories(dirs, rom, "gameboy"); };
    std::ofstream(root / "data.bin", std::ios::binary) << "hello";
    std::ofstream(root / "game.sym") << "; File generated by rgblink\n00:0001 Target\n";
    manifest(R"(,"symbols":"game.sym","regions":[{"name":"pool","size":8,"file":"data.bin"}],"patches":[{"symbol":"Target","expected":"62","replacement":"64"}]})");
    auto success = load();
    assert(success.prepared && success.error.empty());
    assert(success.prepared->rom == std::vector<std::uint8_t>({'a','d','c'}));
    assert(rom[1] == 'b');
    const auto id = success.prepared->mods[0].regions.at("pool");
    assert(success.prepared->host.region(id)[0] == 'h');
    assert(success.prepared->host.region(id)[7] == 0);
    manifest(R"(,"regions":[{"name":"pool","size":4,"file":"data.bin"}]})");
    assert(!load().prepared);
    manifest(R"(,"symbols":"../escape.sym"})");
    assert(!load().prepared);
    std::filesystem::create_symlink("/etc/hosts", root / "escape");
    manifest(R"(,"symbols":"escape"})");
    assert(!load().prepared);
    manifest(R"(,"priority":-1})");
    assert(!load().prepared);
    manifest(R"(,"priority":1.5})");
    assert(!load().prepared);
    manifest(R"(,"regions":[{"name":"pool","size":0}]})");
    assert(!load().prepared);
    manifest(R"(,"regions":[{"name":"pool","size":1},{"name":"pool","size":1}]})");
    assert(!load().prepared);
    manifest(R"(,"schemaVersion":1})");
    assert(!load().prepared);
    manifest(R"(,"nativeModule":"module.so"})");
    assert(!load().prepared);
    std::ofstream(root / "module.so") << "deliberately not a library";
    manifest(R"(,"nativeModule":"module.so"})");
    const auto nativePrepared = load();
    assert(nativePrepared.prepared);
    assert(nativePrepared.prepared->mods[0].nativeModule == root / "module.so");
    manifest(R"(,"trampolines":[{"symbol":"Target","hookId":1}]})");
    assert(!load().prepared); // A hook declaration must have a loadable module.
    manifest(R"(,"nativeModule":"module.so","trampolines":[{"symbol":"Target","hookId":0}]})");
    assert(!load().prepared); // Hook IDs are explicit and nonzero.
    manifest(R"(,"nativeModule":"module.so","trampolines":[{"symbol":"Target","hookId":1,"extra":2}]})");
    assert(!load().prepared); // Reject undeclared trampoline fields.
    manifest(R"(,"nativeModule":"module.so","trampolines":[{"symbol":"Target","hookId":1}]})");
    const auto trampolinePrepared = load();
    assert(trampolinePrepared.prepared && trampolinePrepared.prepared->mods[0].trampolines.size() == 1);
    assert(trampolinePrepared.prepared->mods[0].trampolines[0].symbol == "Target");
    manifest(R"(,"patches":[{"bank":0,"address":3,"expected":"61","replacement":"62"}]})");
    assert(!load().prepared);
    manifest(R"(,"patches":[{"bank":0,"address":0,"expected":"61","replacement":"6263"}]})");
    assert(!load().prepared);
    std::ofstream(root / "manifest.json") << "{";
    assert(!load().prepared);
    manifest(R"(,"patches":[{"bank":0,"address":1,"expected":"00","replacement":"64"}]})");
    assert(!load().prepared);
    manifest(R"(,"patches":[{"bank":0,"address":1,"expected":"6263","replacement":"6465"},{"bank":0,"address":2,"expected":"65","replacement":"66"}]})");
    assert(!load().prepared);
    manifest("}");
    const std::vector<std::uint8_t> wrongRom{'x'};
    assert(!loadModDirectories(dirs, wrongRom, "gameboy").prepared);
    assert(!loadModDirectories(dirs, rom, "gamegear").prepared);
    const std::vector<std::filesystem::path> duplicates{root, root};
    assert(!loadModDirectories(duplicates, rom, "gameboy").prepared);
    // Packages are sorted by priority, then ID, independent of selection order.
    const auto second = root / "second";
    std::filesystem::create_directory(second);
    auto secondText = prefix;
    secondText.replace(secondText.find("demo"), 4, "another");
    std::ofstream(second / "manifest.json") << secondText << "}";
    const std::vector<std::filesystem::path> stack{root, second};
    const auto stacked = loadModDirectories(stack, rom, "gameboy");
    assert(stacked.prepared && stacked.prepared->mods[0].id == "another");
    manifest(R"(,"symbols":"game.sym"})");
    std::ofstream(root / "game.sym") << "00:0001 Target\n00:0002 Target\n";
    assert(!load().prepared);
    std::ofstream(root / "game.sym") << "00:00zz Target\n";
    assert(!load().prepared);
    // Late failure never publishes earlier region or patch changes.
    manifest(R"(,"regions":[{"name":"pool","size":8,"file":"data.bin"}],"patches":[{"bank":0,"address":0,"expected":"61","replacement":"70"},{"bank":0,"address":2,"expected":"00","replacement":"71"}]})");
    assert(!load().prepared && rom[0] == 'a');
    assert(success.prepared->host.region(id)[0] == 'h');
}
