'use strict';
const $=id=>document.getElementById(id),hex=(n,width=2)=>n.toString(16).toUpperCase().padStart(width,'0');
let meta=null,snapshot=null,busy=false,connected=false;
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function image(canvas,rgba,width,height){if(rgba.length!==width*height*8)throw Error('Invalid image extent');const bytes=new Uint8ClampedArray(width*height*4);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(rgba.slice(i*2,i*2+2),16);canvas.width=width;canvas.height=height;canvas.getContext('2d').putImageData(new ImageData(bytes,width,height),0,0);}
function dump(values,base=0){let out='';for(let i=0;i<values.length;i+=16)out+=hex(base+i,4)+'  '+values.slice(i,i+16).map(x=>hex(x)).join(' ')+'\n';return out;}
function updateControls(){const paused=connected&&snapshot&&snapshot.cpu.state===1;for(const id of ['step','read','write','break','clear'])$(id).disabled=busy||!paused;$('run').disabled=busy||!paused;$('pause').disabled=busy||!connected||!snapshot||snapshot.cpu.state!==2;}
function render(){const s=snapshot;$('sequence').textContent='SAMPLE '+s.sequence;$('state').textContent=['DETACHED','PAUSED','RUNNING','FAULTED'][s.cpu.state];$('cycles').textContent=s.cycles+' cycles';$('generation').textContent='GEN '+s.cpu.generation;$('registers').replaceChildren();meta.registerNames.forEach((name,i)=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=hex(s.cpu.registers[i],4);row.append(dt,dd);$('registers').append(row);});image($('frame'),s.frame.rgba,160,144);if($('overlay').checked){const ctx=$('frame').getContext('2d');ctx.fillStyle='rgba(235,132,65,.5)';s.semantics.forEach((n,i)=>{if(n!==null&&s.resources[n]&&s.resources[n].kind==='Sprite')ctx.fillRect(i%160,Math.floor(i/160),1,1);});}
image($('atlas'),meta.core==='gamegear'&&$('palette-bank').value==='1'?s.atlas.rgbaSprite:s.atlas.rgba,s.atlas.width,s.atlas.height);
$('palette').replaceChildren();for(let i=0;i<s.paletteRgba.length;i+=8){const swatch=document.createElement('span');swatch.className='swatch';swatch.style.backgroundColor='#'+s.paletteRgba.slice(i,i+6);swatch.title='Color '+i/8;$('palette').append(swatch);}
$('tile-count').textContent=s.atlas.tileCount+' patterns';$('atlas-note').textContent=meta.core==='gamegear'?'4 BPP · VDP':'2 BPP · DMG';$('palette-bank').disabled=meta.core!=='gamegear';$('sprite-title').textContent=meta.core==='gamegear'?'VDP sprite attribute table':'OAM · 40 sprite entries';$('oam').textContent=meta.core==='gamegear'?s.sprites.map((row,i)=>hex(i)+'  Y '+hex(row[0])+' X '+hex(row[1])+' TILE '+hex(row[2])).join('\n'):dump(s.oam,0xfe00);$('video-registers').textContent=dump(s.videoRegisters);const page=Math.max(0,Math.min(Math.floor(Number($('vram-page').value)||0),s.vram.length/256-1));$('vram-page').max=s.vram.length/256-1;$('vram').textContent=dump(s.vram.slice(page*256,page*256+256),(meta.core==='gameboy'?0x8000:0)+page*256);$('drops').textContent=s.droppedSnapshots+' replaced snapshots · video sample '+s.videoSequence+' · baseline interpreter · '+(s.frame.displayEnabled?'display enabled':'display disabled');updateControls();}
async function refresh(){try{if(!meta){const response=await fetch('/api/meta',{cache:'no-store'});if(!response.ok)throw Error('Metadata unavailable');meta=await response.json();$('core').textContent=meta.core==='gamegear'?'SEGA GAME GEAR / Z80':'GAME BOY / LR35902';$('rom-hash').textContent=meta.romSha256;$('source-hash').textContent=meta.sourceSha256;}const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw Error('Snapshot unavailable');const s=await response.json();if(s.error)throw Error(s.error);if(s.core!==meta.core||s.schemaVersion!==1)throw Error('Snapshot contract changed');snapshot=s;if(!connected)message('Snapshot ready');connected=true;$('connection').textContent='Local machine connected';$('lamp').classList.add('connected');render();}catch(e){connected=false;$('connection').textContent='Disconnected';$('lamp').classList.remove('connected');message(e.message,true);updateControls();}finally{setTimeout(refresh,100);}}
async function command(operation,extra={}){if(busy||!snapshot||!connected)return;busy=true;updateControls();try{const response=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json','X-Time-Token':meta.token},body:JSON.stringify({operation,generation:snapshot.cpu.generation,pauseId:snapshot.cpu.pauseId,...extra})});const reply=await response.json();if(!response.ok||reply.error)throw Error(reply.error?['','Detached','Machine is running','Snapshot changed; retry','Invalid values','Unsupported capability','Machine fault'][reply.error]||String(reply.error):'Request rejected');message(operation+' accepted');if(operation==='inspect')$('memory').textContent=dump(reply.memory,extra.address);}catch(e){message(e.message,true);}finally{busy=false;updateControls();}}
function address(id,max){const value=$(id).value;if(!/^[0-9a-f]+$/i.test(value)||parseInt(value,16)>max)throw Error('Enter a valid hexadecimal value');return parseInt(value,16);}
function action(fn){try{fn();}catch(e){message(e.message,true);}}
$('run').onclick=()=>command('continue');$('pause').onclick=()=>command('pause');$('step').onclick=()=>action(()=>{const steps=Number($('steps').value);if(!Number.isInteger(steps)||steps<1||steps>10000000)throw Error('Step count must be 1–10000000');command('step',{steps});});$('read').onclick=()=>action(()=>command('inspect',{address:address('address',65504),length:32}));$('write').onclick=()=>action(()=>command('edit',{bytes:[{address:address('address',65535),value:address('value',255)}]}));$('break').onclick=()=>action(()=>command('rules',{breakpoints:[{address:address('breakpoint',65535)}],watchpoints:[]}));$('clear').onclick=()=>command('rules',{breakpoints:[],watchpoints:[]});for(const id of ['overlay','vram-page','palette-bank'])$(id).onchange=()=>{if(snapshot)render();};
$('frame').onmousemove=e=>{if(!snapshot)return;const rect=$('frame').getBoundingClientRect(),x=Math.min(159,Math.max(0,Math.floor((e.clientX-rect.left)*160/rect.width))),y=Math.min(143,Math.max(0,Math.floor((e.clientY-rect.top)*144/rect.height)));const index=snapshot.semantics[y*160+x],r=index===null?null:snapshot.resources[index];$('pixel').textContent=r?`Pixel ${x},${y} · ${r.kind} ${r.index} · $${hex(r.address,4)} · ${r.label}`:`Pixel ${x},${y} · no decoded resource`;};$('atlas').onclick=e=>{if(!snapshot)return;const rect=$('atlas').getBoundingClientRect(),x=Math.min(15,Math.max(0,Math.floor((e.clientX-rect.left)*16/rect.width))),y=Math.min(snapshot.atlas.tileCount/16-1,Math.max(0,Math.floor((e.clientY-rect.top)*(snapshot.atlas.height/8)/rect.height))),index=y*16+x;const addr=(meta.core==='gameboy'?0x8000:0)+index*(meta.core==='gameboy'?16:32);$('tile').textContent=`Pattern ${index} · backing $${hex(addr,4)} · ${meta.core==='gameboy'?16:32} bytes`;};updateControls();refresh();
