#include "Project.hpp"
#include <fstream>
namespace BMMQ::Space {
void exportHtml(const Project& project,const std::filesystem::path& path){
    auto doc=project.document().dump();
    // Embedded JSON must not terminate its script element; it is never executable code.
    for(size_t pos=0;(pos=doc.find('<',pos))!=std::string::npos;pos+=6)doc.replace(pos,1,"\\u003c");
    std::ofstream f(path);if(!f)throw std::runtime_error("cannot write viewer");
    f<<R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>S.P.A.C.E. / captured program</title>
<style>
:root{color-scheme:dark;--bg:#101417;--panel:#192126;--line:#34434b;--ink:#e7ecea;--muted:#9aacae;--accent:#c9f276;--warn:#ffb86b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px ui-monospace,monospace}header{height:76px;padding:14px 22px;border-bottom:1px solid var(--line);display:flex;gap:24px;align-items:center}h1{font-size:22px;letter-spacing:4px;margin:0;color:var(--accent)}small{color:var(--muted)}button,input{background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:3px;padding:8px;font:inherit}button{cursor:pointer}button:hover,button:focus{border-color:var(--accent)}main{display:grid;grid-template-columns:minmax(0,1fr) 370px;height:calc(100vh - 112px)}#canvas{width:100%;height:100%;background-image:radial-gradient(#2a353b 1px,transparent 1px);background-size:22px 22px;touch-action:none}aside{overflow:auto;padding:18px;border-left:1px solid var(--line);background:#131a1e}h2{font-size:14px;text-transform:uppercase;letter-spacing:2px;color:var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6}footer{height:36px;padding:8px 22px;color:var(--muted);border-top:1px solid var(--line)}.node rect{fill:var(--panel);stroke:var(--line)}.node.selected rect{stroke:var(--accent);stroke-width:2}.node text{fill:var(--ink);font-size:12px}.edge{fill:none;stroke:#749095;stroke-width:1.5}.edge-label{fill:var(--muted);font-size:10px}.unknown rect{stroke:var(--warn);stroke-dasharray:4 4}.unknown text{fill:var(--warn)}#notice{color:var(--warn)}.pill{padding:5px;border:1px solid var(--line);display:inline-block;margin:3px 0}.row{margin:12px 0}.neighbors button{margin:3px}@media(max-width:800px){main{grid-template-columns:minmax(0,1fr) 280px}header{gap:10px;padding:10px}header small{display:none}}
</style>
<header><div><h1>S.P.A.C.E.</h1><small>PROGRAM OBSERVATORY / CAPTURED REVISION</small></div><input id="search" aria-label="Find address or instruction" placeholder="Find address / instruction"><button id="find">Find</button><button id="fit">Reset view</button><button id="download">Save annotations</button><label>Load capture <input type="file" id="file" accept=".json" style="width:180px"></label></header>
<main><svg id="canvas" aria-label="Captured control flow graph"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="#749095"/></marker></defs><g id="world"></g></svg><aside><h2>Capture</h2><div id="summary"></div><div id="notice"></div><h2>Selected block</h2><div id="inspector">Select a block to inspect its evidence.</div></aside></main><footer id="footer">Pan background · wheel to zoom · drag blocks · arrows follow control flow</footer>
<script id="capture" type="application/json">)HTML"<<doc<<R"HTML(</script><script>
'use strict';let project,selected=null,positions=new Map(),view={x:30,y:30,z:1};const svg=document.querySelector('#canvas'),world=document.querySelector('#world');
const ns='http://www.w3.org/2000/svg';function elem(tag,attrs={},text){let e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}function html(tag,text){let e=document.createElement(tag);e.textContent=text;return e}function hex(n){return '$'+Number(n).toString(16).padStart(4,'0')}function transform(){world.setAttribute('transform',`translate(${view.x} ${view.y}) scale(${view.z})`)}
function validate(p){if(p.schemaVersion!==1||p.core!=='gameboy'||!/^[a-f0-9]{64}$/.test(p.romSha256)||!Array.isArray(p.blocks)||!Array.isArray(p.graphEdges)||!p.instructions||!Array.isArray(p.dependencies)||!Array.isArray(p.gaps))throw Error('Unsupported or malformed capture');let ids=new Set();for(let b of p.blocks){if(ids.has(b.id)||!Array.isArray(b.instructions)||b.instructions.some(i=>!p.instructions[i]))throw Error('Invalid block reference');ids.add(b.id)}for(let e of p.graphEdges)if(!ids.has(e.from)||(!ids.has(e.to)&&!e.to.startsWith('unresolved:')))throw Error('Invalid edge');}
function load(p){validate(p);project=p;if(!project.blocks.some(b=>b.id===selected))selected=null;let summary=document.querySelector('#summary');summary.replaceChildren(html('div','Revision '+p.revision),html('small','ROM '+p.romSha256.slice(0,16)+'…'),html('div',p.blocks.length+' blocks / '+p.dependencies.length+' access observations'));document.querySelector('#notice').textContent=p.gaps.length?'INCOMPLETE CAPTURE: '+p.gaps.map(g=>g.reason).join('; '):'Unobserved paths remain unresolved; this is not a completeness proof.';layout();draw();inspect();}
function layout(){// Deterministic traversal; back edges do not keep advancing levels.
 let ids=project.blocks.map(b=>b.id).sort(),known=new Set(ids),depth=new Map(),todo=[];let incoming=new Set(project.graphEdges.map(e=>e.to));for(let id of ids)if(!incoming.has(id)){depth.set(id,0);todo.push(id)}for(let id of ids){if(!depth.has(id)&&todo.length===0){depth.set(id,0);todo.push(id)}while(todo.length){let from=todo.shift();for(let e of project.graphEdges.filter(e=>e.from===from).sort((a,b)=>a.to.localeCompare(b.to)))if(known.has(e.to)&&!depth.has(e.to)){depth.set(e.to,depth.get(from)+1);todo.push(e.to)}}}let levels=new Map();for(let id of ids){let d=depth.get(id)||0,n=levels.get(d)||0;levels.set(d,n+1);if(!positions.has(id))positions.set(id,{x:n*340,y:d*220})}let u=0;for(let e of project.graphEdges)if(!known.has(e.to)&&!positions.has(e.to))positions.set(e.to,{x:360*(u++),y:(Math.max(0,...depth.values())+1)*220});}
function draw(){world.replaceChildren();let by=new Map(project.blocks.map(b=>[b.id,b]));for(let e of project.graphEdges){let a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)continue;let path=e.from===e.to?`M${a.x+290},${a.y+70} C${a.x+380},${a.y-70} ${a.x-90},${a.y-70} ${a.x},${a.y+70}`:`M${a.x+145},${a.y+155} C${a.x+145},${a.y+185} ${b.x+145},${b.y-30} ${b.x+145},${b.y}`;world.append(elem('path',{d:path,class:'edge','marker-end':'url(#arrow)'}),elem('text',{x:(a.x+b.x)/2+155,y:(a.y+b.y)/2+78,class:'edge-label'},e.kind))}let ids=new Set([...by.keys(),...project.graphEdges.map(e=>e.to)]);for(let id of ids){let p=positions.get(id);if(!p)continue;let b=by.get(id),g=elem('g',{transform:`translate(${p.x} ${p.y})`,class:'node '+(b?'':'unknown ')+(id===selected?'selected':''),'data-id':id,tabindex:0,role:'button','aria-label':b?'Block '+hex(project.instructions[b.instructions[0]].address):id});g.append(elem('rect',{width:290,height:155,rx:3}));let lines=b?[hex(project.instructions[b.instructions[0]].address)+' / '+id.slice(0,9),...b.instructions.slice(0,5).map(i=>hex(project.instructions[i].address)+'  '+project.instructions[i].text),'conversion: not assessed']:['? UNRESOLVED',id.slice(11)];lines.forEach((t,i)=>g.append(elem('text',{x:13,y:23+i*19},t)));g.addEventListener('click',()=>{selected=id;draw();inspect()});g.addEventListener('keydown',e=>{if(e.key==='Enter'){selected=id;draw();inspect()}});g.addEventListener('pointerdown',e=>{e.stopPropagation();drag={id,x:e.clientX,y:e.clientY,px:p.x,py:p.y};svg.setPointerCapture(e.pointerId)});world.append(g)}transform();}
function inspect(){let box=document.querySelector('#inspector');box.replaceChildren();let b=project.blocks.find(b=>b.id===selected);if(!b){box.append(html('p',selected?'Unresolved destination; no observed code is assigned.':'Select a block to inspect its evidence.'));return}box.append(html('div','Block '+selected.slice(0,16)),html('div','Conversion: '+b.conversion),html('div','Verification: '+b.verification));let instructions=b.instructions.map(i=>project.instructions[i]);let sections=[['Instructions',instructions.map(n=>hex(n.address)+' '+n.bytes+' '+n.text).join('\n')],['Current registers',JSON.stringify(b.registers,null,2)],['Current sparse snapshot',JSON.stringify(b.snapshot,null,2)],['History',JSON.stringify(b.lastVisit,null,2)],['Boundary events (last 64)',JSON.stringify((project.boundaries||[]).slice(-64),null,2)],['Hardware access facts',[...new Set(instructions.flatMap(n=>n.hardware))].join(', ')||'None observed'],['Execution sources',JSON.stringify(project.dependencies.filter(d=>b.instructions.includes(d.instruction)&&d.executionSource).map(d=>({location:d.location,source:d.executionSource,supplier:d.executionSupplier})),null,2)],['Dependencies',JSON.stringify(project.dependencies.filter(d=>b.instructions.includes(d.instruction)),null,2)],['Annotations',JSON.stringify(project.annotations[selected]||[],null,2)]];for(let[name,value]of sections){box.append(html('h2',name),html('pre',value))}let neighbors=html('div','');neighbors.className='neighbors';for(let e of project.graphEdges.filter(e=>e.from===selected||e.to===selected)){let id=e.from===selected?e.to:e.from;let btn=html('button',(e.from===selected?'→ ':'← ')+e.kind+' '+id.slice(0,9));btn.onclick=()=>{selected=id;let p=positions.get(id);view.x=40-p.x*view.z;view.y=40-p.y*view.z;draw();inspect()};neighbors.append(btn)}box.append(html('h2','Control flow'),neighbors);let note=document.createElement('textarea');note.setAttribute('aria-label','Analysis annotation');note.style.width='100%';let kind=document.createElement('select');for(let value of ['inference','confirmed','correction']){let option=document.createElement('option');option.value=value;option.textContent=value;kind.append(option)}let add=html('button','Add annotation');add.onclick=()=>{if(!note.value.trim())return;(project.annotations[selected]??=[]).push({kind:kind.value,text:note.value.trim()});project.revision=(BigInt(project.revision)+1n).toString();inspect()};box.append(html('h2','Annotate captured evidence'),kind,note,add)}
document.querySelector('#download').onclick=()=>{let url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='space-annotated.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};let drag=null;svg.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;if(drag.id){positions.set(drag.id,{x:drag.px+(e.clientX-drag.x)/view.z,y:drag.py+(e.clientY-drag.y)/view.z});draw()}else{view.x=drag.vx+e.clientX-drag.x;view.y=drag.vy+e.clientY-drag.y;transform()}});svg.addEventListener('pointerup',()=>drag=null);svg.addEventListener('wheel',e=>{e.preventDefault();let rect=svg.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,z=Math.max(.15,Math.min(3,view.z*Math.exp(-e.deltaY*.001)));view.x=x-(x-view.x)*z/view.z;view.y=y-(y-view.y)*z/view.z;view.z=z;transform()},{passive:false});document.querySelector('#fit').onclick=()=>{view={x:30,y:30,z:1};transform()};document.querySelector('#find').onclick=()=>{let q=document.querySelector('#search').value.toLowerCase(),b=project.blocks.find(b=>b.id.includes(q)||b.instructions.some(i=>{let n=project.instructions[i];return hex(n.address).includes(q)||n.text.toLowerCase().includes(q)}));if(b){selected=b.id;let p=positions.get(b.id);view.x=30-p.x*view.z;view.y=30-p.y*view.z;draw();inspect()}};document.querySelector('#file').onchange=async e=>{try{let file=e.target.files[0];if(file.size>128*1024*1024)throw Error('Capture exceeds 128 MiB');load(JSON.parse(await file.text()))}catch(err){document.querySelector('#notice').textContent=err.message}};load(JSON.parse(document.querySelector('#capture').textContent));
</script></html>)HTML";
    f.close();if(!f)throw std::runtime_error("viewer write failed");
}
}
