# Runtime dependencies remain outside the repository; configure never downloads.
option(TIME_SCRIPT_ENABLE_LUA "Enable Lua 5.4 scripting" ON)
option(TIME_SCRIPT_ENABLE_PYTHON "Enable isolated Python scripting workers" ON)
set(TIME_LUA_SOURCE_DIR "" CACHE PATH "Optional Lua 5.4 source tree for cross builds")
set(TIME_QUICKJS_SOURCE_DIR "" CACHE PATH "QuickJS source tree (2026-06-04 interface)")
set(TIME_SCRIPT_PYTHON_EXECUTABLE "${Python3_EXECUTABLE}" CACHE FILEPATH "Python interpreter on the execution host")
add_library(time-script-runtime STATIC
    machine/plugins/script/ScriptEngine.cpp machine/plugins/script/ScriptService.cpp
    machine/plugins/script/adapters/LuaRuntime.cpp
    machine/plugins/script/adapters/PythonRuntime.cpp
    machine/plugins/script/adapters/QuickJsRuntime.cpp)
target_link_libraries(time-script-runtime PUBLIC time-machine-runtime-common time-space-core-contract Threads::Threads nlohmann_json::nlohmann_json)
if(TIME_SCRIPT_ENABLE_LUA)
    if(TIME_LUA_SOURCE_DIR)
        set(lua_units lapi lcode lctype ldebug ldo ldump lfunc lgc llex lmem lobject lopcodes lparser lstate lstring ltable ltm lundump lvm lzio lauxlib lbaselib lmathlib lstrlib ltablib lutf8lib)
        set(lua_sources)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/lua-units")
        foreach(unit ${lua_units})
            # Lua supports C++ exception-based protected calls. Preserve its
            # public C linkage while avoiding longjmp across instrumentation.
            set(wrapper "${CMAKE_CURRENT_BINARY_DIR}/lua-units/${unit}.cpp")
            file(WRITE "${wrapper}" "#define LUA_CORE\n#include \"${TIME_LUA_SOURCE_DIR}/src/lprefix.h\"\nextern \"C\" {\n#include \"${TIME_LUA_SOURCE_DIR}/src/lua.h\"\n#include \"${TIME_LUA_SOURCE_DIR}/src/lauxlib.h\"\n#include \"${TIME_LUA_SOURCE_DIR}/src/lualib.h\"\n}\n#include \"${TIME_LUA_SOURCE_DIR}/src/${unit}.c\"\n")
            list(APPEND lua_sources "${wrapper}")
        endforeach()
        file(STRINGS "${TIME_LUA_SOURCE_DIR}/src/lua.h" lua_version REGEX "^#define LUA_VERSION_NUM[ \t]+504$")
        if(NOT lua_version)
            message(FATAL_ERROR "TIME_LUA_SOURCE_DIR must contain Lua 5.4")
        endif()
        add_library(time-lua-runtime STATIC ${lua_sources})
        target_include_directories(time-lua-runtime PUBLIC "${TIME_LUA_SOURCE_DIR}/src")
        target_link_libraries(time-lua-runtime PUBLIC m ${CMAKE_DL_LIBS})
        target_compile_options(time-lua-runtime PRIVATE -w)
        target_link_libraries(time-script-runtime PRIVATE time-lua-runtime)
        target_compile_definitions(time-script-runtime PRIVATE TIME_SCRIPT_LUA=1)
    else()
        find_package(Lua 5.4 QUIET)
        if(LUA_FOUND AND LUA_VERSION_STRING VERSION_LESS 5.5)
            if(BMMQ_ENABLE_TSAN)
                message(FATAL_ERROR "Lua TSAN checks require TIME_LUA_SOURCE_DIR for the C++ protected-call build")
            endif()
            target_include_directories(time-script-runtime PRIVATE ${LUA_INCLUDE_DIR})
            target_link_libraries(time-script-runtime PRIVATE ${LUA_LIBRARIES})
            target_compile_definitions(time-script-runtime PRIVATE TIME_SCRIPT_LUA=1)
        endif()
    endif()
endif()
if(TIME_SCRIPT_ENABLE_PYTHON)
    target_compile_definitions(time-script-runtime PRIVATE TIME_SCRIPT_PYTHON=1
        TIME_SCRIPT_PYTHON_EXECUTABLE="${TIME_SCRIPT_PYTHON_EXECUTABLE}"
        TIME_SCRIPT_PYTHON_WORKER="${CMAKE_CURRENT_SOURCE_DIR}/machine/plugins/script/adapters/PythonRuntime.py")
endif()
if(TIME_QUICKJS_SOURCE_DIR)
    set(quickjs_sources)
    foreach(unit quickjs dtoa libregexp libunicode cutils)
        list(APPEND quickjs_sources "${TIME_QUICKJS_SOURCE_DIR}/${unit}.c")
    endforeach()
    add_library(time-quickjs-runtime STATIC ${quickjs_sources})
    target_include_directories(time-quickjs-runtime SYSTEM PUBLIC "${TIME_QUICKJS_SOURCE_DIR}")
    target_compile_definitions(time-quickjs-runtime PRIVATE _GNU_SOURCE CONFIG_VERSION="2026-06-04")
    target_compile_options(time-quickjs-runtime PRIVATE -fwrapv -w)
    target_link_libraries(time-quickjs-runtime PUBLIC m Threads::Threads ${CMAKE_DL_LIBS})
    target_compile_definitions(time-script-runtime PRIVATE TIME_SCRIPT_QUICKJS=1)
    target_link_libraries(time-script-runtime PRIVATE time-quickjs-runtime)
endif()
add_executable(time-script machine/plugins/script/main.cpp)
target_link_libraries(time-script PRIVATE time-script-runtime time-gameboy-interpreter-core time-gamegear-core)
add_executable(time-smoke-scripting tests/smoke_scripting.cpp)
target_link_libraries(time-smoke-scripting PRIVATE time-script-runtime time-gameboy-interpreter-core time-gamegear-core)
add_test(NAME smoke-scripting COMMAND time-smoke-scripting)
set_tests_properties(smoke-scripting PROPERTIES TIMEOUT 90)
add_test(NAME smoke-scripting-cli COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/smoke_scripting_cli.py $<TARGET_FILE:time-script>)
set_tests_properties(smoke-scripting-cli PROPERTIES TIMEOUT 90)

add_test(NAME smoke-qemu-ctest-launchers COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/smoke_qemu_ctest.py)

if(CMAKE_CROSSCOMPILING)
    set_tests_properties(smoke-scripting PROPERTIES ENVIRONMENT "TIME_SCRIPT_TEST_TIMEOUT_MS=30000")
endif()
