if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_library(time-visual-authoring STATIC machine/plugins/video/authoring/Authoring.cpp)
    target_link_libraries(time-visual-authoring PUBLIC time-script-runtime)
    add_executable(time-visual-author machine/plugins/video/authoring/main.cpp)
    target_link_libraries(time-visual-author PRIVATE time-visual-authoring)
    add_executable(time-smoke-visual-authoring tests/smoke_visual_authoring.cpp)
    target_link_libraries(time-smoke-visual-authoring PRIVATE time-visual-authoring time-gameboy-interpreter-core time-gamegear-core)
    add_test(NAME smoke-visual-authoring COMMAND time-smoke-visual-authoring)
    set_tests_properties(smoke-visual-authoring PROPERTIES TIMEOUT 90)
    if(CMAKE_CROSSCOMPILING)
        set_tests_properties(smoke-visual-authoring PROPERTIES ENVIRONMENT "TIME_SCRIPT_TEST_TIMEOUT_MS=30000")
    endif()
    find_program(TIME_AUTHORING_NODE_EXECUTABLE NAMES node nodejs)
    if(NOT TIME_AUTHORING_NODE_EXECUTABLE)
        message(FATAL_ERROR "Node.js is required for the visual presentation contract tests")
    endif()
    if(TIME_AUTHORING_NODE_EXECUTABLE)
        add_test(NAME smoke-visual-presentation COMMAND ${TIME_AUTHORING_NODE_EXECUTABLE}
            ${CMAKE_CURRENT_SOURCE_DIR}/tests/smoke_visual_presentation.js)
    endif()
    add_test(NAME smoke-visual-authoring-cli COMMAND ${Python3_EXECUTABLE}
        ${CMAKE_CURRENT_SOURCE_DIR}/tests/smoke_visual_authoring_cli.py $<TARGET_FILE:time-visual-author>)
    set_tests_properties(smoke-visual-authoring-cli PROPERTIES TIMEOUT 90)
endif()
